services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: go_plate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  email_server:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  database:
