version:
  "3"

  # Change only if you know what you are doing

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  install:
    desc: Install development dependencies
    silent: true
    cmds:
      - go mod tidy
      - go install github.com/cosmtrek/air@latest
      - echo "All dependencies installed successfully..."

  start:
    desc: Start the development server
    cmds:
      - docker compose up -d
      - air -c .air.toml

  stop:
    desc: Stop the development server
    cmds:
      - docker compose down

  gen:
    desc: Generate code
    cmds:
      - cd cmd/main
      - go generate ./...
