version: "3"

vars:
  AIR_ENABLED: "false"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  generate:
    cmds:
      - cd cmd/example && go generate .

  # Run application outside Docker
  start:
    cmds:
      - CUSTOM="Air" docker-compose up --build example

  stop:
    cmds:
      - docker-compose down
