version:
  "3"

  # Change only if you know what you are doing

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  # Run application outside Docker
  start:
    desc: Start the development server
    cmds:
      - CUSTOM="Air" docker compose up --build example

  stop:
    desc: Stop the development server
    cmds:
      - docker compose down

  install:
    desc: Install dependencies
    cmds:
      - go mod tidy

  gen:
    desc: Generate code
    cmds:
      - cd cmd/main
      - go generate ./...
