// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "disable_time", Type: field.TypeTime, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, Nullable: true, Size: 2147483647},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "lang_tag", Type: field.TypeString, Size: 2147483647, Default: "en-US"},
		{Name: "location", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "timezone", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "account_profile", Type: field.TypeString, Unique: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profiles_accounts_profile",
				Columns:    []*schema.Column{ProfilesColumns[9]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		ProfilesTable,
	}
)

func init() {
	ProfilesTable.ForeignKeys[0].RefTable = AccountsTable
}
