// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go_plate/internal/ent/account"
	"go_plate/internal/ent/predicate"
	"go_plate/internal/ent/profile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileUpdate is the builder for updating Profile entities.
type ProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileMutation
}

// Where appends a list predicates to the ProfileUpdate builder.
func (pu *ProfileUpdate) Where(ps ...predicate.Profile) *ProfileUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUsername sets the "username" field.
func (pu *ProfileUpdate) SetUsername(s string) *ProfileUpdate {
	pu.mutation.SetUsername(s)
	return pu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableUsername(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetUsername(*s)
	}
	return pu
}

// ClearUsername clears the value of the "username" field.
func (pu *ProfileUpdate) ClearUsername() *ProfileUpdate {
	pu.mutation.ClearUsername()
	return pu
}

// SetDisplayName sets the "display_name" field.
func (pu *ProfileUpdate) SetDisplayName(s string) *ProfileUpdate {
	pu.mutation.SetDisplayName(s)
	return pu
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableDisplayName(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetDisplayName(*s)
	}
	return pu
}

// ClearDisplayName clears the value of the "display_name" field.
func (pu *ProfileUpdate) ClearDisplayName() *ProfileUpdate {
	pu.mutation.ClearDisplayName()
	return pu
}

// SetBio sets the "bio" field.
func (pu *ProfileUpdate) SetBio(s string) *ProfileUpdate {
	pu.mutation.SetBio(s)
	return pu
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableBio(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetBio(*s)
	}
	return pu
}

// ClearBio clears the value of the "bio" field.
func (pu *ProfileUpdate) ClearBio() *ProfileUpdate {
	pu.mutation.ClearBio()
	return pu
}

// SetLangTag sets the "lang_tag" field.
func (pu *ProfileUpdate) SetLangTag(s string) *ProfileUpdate {
	pu.mutation.SetLangTag(s)
	return pu
}

// SetNillableLangTag sets the "lang_tag" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableLangTag(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetLangTag(*s)
	}
	return pu
}

// SetLocation sets the "location" field.
func (pu *ProfileUpdate) SetLocation(s string) *ProfileUpdate {
	pu.mutation.SetLocation(s)
	return pu
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableLocation(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetLocation(*s)
	}
	return pu
}

// ClearLocation clears the value of the "location" field.
func (pu *ProfileUpdate) ClearLocation() *ProfileUpdate {
	pu.mutation.ClearLocation()
	return pu
}

// SetTimezone sets the "timezone" field.
func (pu *ProfileUpdate) SetTimezone(s string) *ProfileUpdate {
	pu.mutation.SetTimezone(s)
	return pu
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableTimezone(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetTimezone(*s)
	}
	return pu
}

// ClearTimezone clears the value of the "timezone" field.
func (pu *ProfileUpdate) ClearTimezone() *ProfileUpdate {
	pu.mutation.ClearTimezone()
	return pu
}

// SetUpdateTime sets the "update_time" field.
func (pu *ProfileUpdate) SetUpdateTime(t time.Time) *ProfileUpdate {
	pu.mutation.SetUpdateTime(t)
	return pu
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (pu *ProfileUpdate) SetAccountID(id string) *ProfileUpdate {
	pu.mutation.SetAccountID(id)
	return pu
}

// SetAccount sets the "account" edge to the Account entity.
func (pu *ProfileUpdate) SetAccount(a *Account) *ProfileUpdate {
	return pu.SetAccountID(a.ID)
}

// Mutation returns the ProfileMutation object of the builder.
func (pu *ProfileUpdate) Mutation() *ProfileMutation {
	return pu.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (pu *ProfileUpdate) ClearAccount() *ProfileUpdate {
	pu.mutation.ClearAccount()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfileUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfileUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfileUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProfileUpdate) defaults() {
	if _, ok := pu.mutation.UpdateTime(); !ok {
		v := profile.UpdateDefaultUpdateTime()
		pu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProfileUpdate) check() error {
	if _, ok := pu.mutation.AccountID(); pu.mutation.AccountCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Profile.account"`)
	}
	return nil
}

func (pu *ProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Username(); ok {
		_spec.SetField(profile.FieldUsername, field.TypeString, value)
	}
	if pu.mutation.UsernameCleared() {
		_spec.ClearField(profile.FieldUsername, field.TypeString)
	}
	if value, ok := pu.mutation.DisplayName(); ok {
		_spec.SetField(profile.FieldDisplayName, field.TypeString, value)
	}
	if pu.mutation.DisplayNameCleared() {
		_spec.ClearField(profile.FieldDisplayName, field.TypeString)
	}
	if value, ok := pu.mutation.Bio(); ok {
		_spec.SetField(profile.FieldBio, field.TypeString, value)
	}
	if pu.mutation.BioCleared() {
		_spec.ClearField(profile.FieldBio, field.TypeString)
	}
	if value, ok := pu.mutation.LangTag(); ok {
		_spec.SetField(profile.FieldLangTag, field.TypeString, value)
	}
	if value, ok := pu.mutation.Location(); ok {
		_spec.SetField(profile.FieldLocation, field.TypeString, value)
	}
	if pu.mutation.LocationCleared() {
		_spec.ClearField(profile.FieldLocation, field.TypeString)
	}
	if value, ok := pu.mutation.Timezone(); ok {
		_spec.SetField(profile.FieldTimezone, field.TypeString, value)
	}
	if pu.mutation.TimezoneCleared() {
		_spec.ClearField(profile.FieldTimezone, field.TypeString)
	}
	if value, ok := pu.mutation.UpdateTime(); ok {
		_spec.SetField(profile.FieldUpdateTime, field.TypeTime, value)
	}
	if pu.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.AccountTable,
			Columns: []string{profile.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.AccountTable,
			Columns: []string{profile.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfileUpdateOne is the builder for updating a single Profile entity.
type ProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileMutation
}

// SetUsername sets the "username" field.
func (puo *ProfileUpdateOne) SetUsername(s string) *ProfileUpdateOne {
	puo.mutation.SetUsername(s)
	return puo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableUsername(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetUsername(*s)
	}
	return puo
}

// ClearUsername clears the value of the "username" field.
func (puo *ProfileUpdateOne) ClearUsername() *ProfileUpdateOne {
	puo.mutation.ClearUsername()
	return puo
}

// SetDisplayName sets the "display_name" field.
func (puo *ProfileUpdateOne) SetDisplayName(s string) *ProfileUpdateOne {
	puo.mutation.SetDisplayName(s)
	return puo
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableDisplayName(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetDisplayName(*s)
	}
	return puo
}

// ClearDisplayName clears the value of the "display_name" field.
func (puo *ProfileUpdateOne) ClearDisplayName() *ProfileUpdateOne {
	puo.mutation.ClearDisplayName()
	return puo
}

// SetBio sets the "bio" field.
func (puo *ProfileUpdateOne) SetBio(s string) *ProfileUpdateOne {
	puo.mutation.SetBio(s)
	return puo
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableBio(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetBio(*s)
	}
	return puo
}

// ClearBio clears the value of the "bio" field.
func (puo *ProfileUpdateOne) ClearBio() *ProfileUpdateOne {
	puo.mutation.ClearBio()
	return puo
}

// SetLangTag sets the "lang_tag" field.
func (puo *ProfileUpdateOne) SetLangTag(s string) *ProfileUpdateOne {
	puo.mutation.SetLangTag(s)
	return puo
}

// SetNillableLangTag sets the "lang_tag" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableLangTag(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetLangTag(*s)
	}
	return puo
}

// SetLocation sets the "location" field.
func (puo *ProfileUpdateOne) SetLocation(s string) *ProfileUpdateOne {
	puo.mutation.SetLocation(s)
	return puo
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableLocation(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetLocation(*s)
	}
	return puo
}

// ClearLocation clears the value of the "location" field.
func (puo *ProfileUpdateOne) ClearLocation() *ProfileUpdateOne {
	puo.mutation.ClearLocation()
	return puo
}

// SetTimezone sets the "timezone" field.
func (puo *ProfileUpdateOne) SetTimezone(s string) *ProfileUpdateOne {
	puo.mutation.SetTimezone(s)
	return puo
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableTimezone(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetTimezone(*s)
	}
	return puo
}

// ClearTimezone clears the value of the "timezone" field.
func (puo *ProfileUpdateOne) ClearTimezone() *ProfileUpdateOne {
	puo.mutation.ClearTimezone()
	return puo
}

// SetUpdateTime sets the "update_time" field.
func (puo *ProfileUpdateOne) SetUpdateTime(t time.Time) *ProfileUpdateOne {
	puo.mutation.SetUpdateTime(t)
	return puo
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (puo *ProfileUpdateOne) SetAccountID(id string) *ProfileUpdateOne {
	puo.mutation.SetAccountID(id)
	return puo
}

// SetAccount sets the "account" edge to the Account entity.
func (puo *ProfileUpdateOne) SetAccount(a *Account) *ProfileUpdateOne {
	return puo.SetAccountID(a.ID)
}

// Mutation returns the ProfileMutation object of the builder.
func (puo *ProfileUpdateOne) Mutation() *ProfileMutation {
	return puo.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (puo *ProfileUpdateOne) ClearAccount() *ProfileUpdateOne {
	puo.mutation.ClearAccount()
	return puo
}

// Where appends a list predicates to the ProfileUpdate builder.
func (puo *ProfileUpdateOne) Where(ps ...predicate.Profile) *ProfileUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfileUpdateOne) Select(field string, fields ...string) *ProfileUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Profile entity.
func (puo *ProfileUpdateOne) Save(ctx context.Context) (*Profile, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfileUpdateOne) SaveX(ctx context.Context) *Profile {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfileUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProfileUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdateTime(); !ok {
		v := profile.UpdateDefaultUpdateTime()
		puo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProfileUpdateOne) check() error {
	if _, ok := puo.mutation.AccountID(); puo.mutation.AccountCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Profile.account"`)
	}
	return nil
}

func (puo *ProfileUpdateOne) sqlSave(ctx context.Context) (_node *Profile, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profile.FieldID)
		for _, f := range fields {
			if !profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Username(); ok {
		_spec.SetField(profile.FieldUsername, field.TypeString, value)
	}
	if puo.mutation.UsernameCleared() {
		_spec.ClearField(profile.FieldUsername, field.TypeString)
	}
	if value, ok := puo.mutation.DisplayName(); ok {
		_spec.SetField(profile.FieldDisplayName, field.TypeString, value)
	}
	if puo.mutation.DisplayNameCleared() {
		_spec.ClearField(profile.FieldDisplayName, field.TypeString)
	}
	if value, ok := puo.mutation.Bio(); ok {
		_spec.SetField(profile.FieldBio, field.TypeString, value)
	}
	if puo.mutation.BioCleared() {
		_spec.ClearField(profile.FieldBio, field.TypeString)
	}
	if value, ok := puo.mutation.LangTag(); ok {
		_spec.SetField(profile.FieldLangTag, field.TypeString, value)
	}
	if value, ok := puo.mutation.Location(); ok {
		_spec.SetField(profile.FieldLocation, field.TypeString, value)
	}
	if puo.mutation.LocationCleared() {
		_spec.ClearField(profile.FieldLocation, field.TypeString)
	}
	if value, ok := puo.mutation.Timezone(); ok {
		_spec.SetField(profile.FieldTimezone, field.TypeString, value)
	}
	if puo.mutation.TimezoneCleared() {
		_spec.ClearField(profile.FieldTimezone, field.TypeString)
	}
	if value, ok := puo.mutation.UpdateTime(); ok {
		_spec.SetField(profile.FieldUpdateTime, field.TypeTime, value)
	}
	if puo.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.AccountTable,
			Columns: []string{profile.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.AccountTable,
			Columns: []string{profile.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profile{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
