// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go_plate/app/database/schema"
	"go_plate/internal/ent/account"
	"go_plate/internal/ent/profile"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescUserID is the schema descriptor for user_id field.
	accountDescUserID := accountFields[1].Descriptor()
	// account.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	account.UserIDValidator = accountDescUserID.Validators[0].(func(string) error)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() string)
	// account.IDValidator is a validator for the "id" field. It is called by the builders before save.
	account.IDValidator = accountDescID.Validators[0].(func(string) error)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescLangTag is the schema descriptor for lang_tag field.
	profileDescLangTag := profileFields[4].Descriptor()
	// profile.DefaultLangTag holds the default value on creation for the lang_tag field.
	profile.DefaultLangTag = profileDescLangTag.Default.(string)
	// profileDescUpdateTime is the schema descriptor for update_time field.
	profileDescUpdateTime := profileFields[7].Descriptor()
	// profile.DefaultUpdateTime holds the default value on creation for the update_time field.
	profile.DefaultUpdateTime = profileDescUpdateTime.Default.(func() time.Time)
	// profile.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	profile.UpdateDefaultUpdateTime = profileDescUpdateTime.UpdateDefault.(func() time.Time)
	// profileDescCreateTime is the schema descriptor for create_time field.
	profileDescCreateTime := profileFields[8].Descriptor()
	// profile.DefaultCreateTime holds the default value on creation for the create_time field.
	profile.DefaultCreateTime = profileDescCreateTime.Default.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() string)
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = profileDescID.Validators[0].(func(string) error)
}
